### ISSUE TITLE
No extension named MIT-SHM could be found on on the server

### ISSUE THREAD

**Issue by ivanmir** [aarzilli/gdlv#26]
Hi All,

I believe I've found some interesting new facts regarding using X11 protocol remotely to draw windows.

It seems that shiny uses xgb (https://github.com/BurntSushi/xgb). 
I've installed xgb and ran the following command:

`go run go/path/src/github.com/BurntSushi/xgb/examples/create-window/main.go`

And with my variable $DISPLAY set, I can see a new Window being displayed. 

It is surprising that shiny complains about SHM and x11driver, where this message is actually being thrown when xgb is being called. I believe shiny project is the culprit (it hasn't been up-to-date with xgb). On top of that shiny has been forked by OakMound team that has been more active with shiny:

https://github.com/oakmound/shiny

The program gdlv uses nucular project - and this is the one that uses shiny. Maybe switching shiny from golang to oakmound?

Can anyone confirm this? 

I really wanted to test gdlv remotely. 
It is really unstable to debug with dlv remotely. 

Best regards,
Ivan

**Comment by aarzilli** [comment]
The reason is described here: https://github.com/golang/go/issues/15100#issuecomment-212925771
I've taken a look at oakmound's fork and it doesn't look like it addresses this problem. 

> I really wanted to test gdlv remotely.

it would be extremely slow, running a headless delve and using `gdlv connect` would be the only practical way of doing it even if shiny worked with remote servers.

>  It is really unstable to debug with dlv remotely.

you should report the bugs that you are encountering,
